### ISSUE TITLE
Exponea ANE build with tiny changes in original SDK code

### ISSUE THREAD

**Issue by gsario** [distriqt/ANE-Exponea#2]
Hi @marchbold ,

The Exponea SDK source code is openly available, and thing is that we need it to track one of the automatically tracked events ("payment") with other name.

I am not sure about when the ANE-s are built the SDK native source code is used, or already built SDK files are used?
If the first is the case, can you please build a new ANE with changed native source code for Exponea?
Any ideas if you can help us?

**Comment by marchbold** [comment]
I don't quite understand the question, can you clarify? 

If you want to change the code I'm happy to rebuild it for you

**Comment by gsario** [comment]
My question is that if we make a new branch of Exponea SDK (https://github.com/Cellense/exponea-ios/) with a tiny code change, can you build the Exponea SDK for us quickly with it? 
It is a bit urgent issue for us.

**Comment by gsario** [comment]
@marchbold here is the modified branch on our fork of Exponea SDK IOS.
https://github.com/plexonic/exponea-ios-sdk/tree/payment-event-fix

Can you please build the ANE from it for us as soon as possible?
(the Android SDK sources stay the same as they were.)

**Comment by gsario** [comment]
@marchbold BTW my emails are bouncing back as spam when trying to email you.

We really need to get this change released asap, so can you please help us with this?
We can even pay you to deliver this ANE change quickly.

**Comment by marchbold** [comment]
Rebuilding now

**Comment by gsario** [comment]
@marchbold, thank you! Just tried the new build - it works as a dev build very well. 
**But when uploading IPA to AppStore we get this error:**

> ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'Pet
> Savers.app/Frameworks/ExponeaSDK.framework/ExponeaSDK' contains incomplete bitcode. To 
> compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

Can you please build it again the way it is described in the error message?

**Comment by marchbold** [comment]
Can you supply the framework and I'll package it with that version for you? or you can just manually update the framework in the ANE zip.

**Comment by gsario** [comment]
We just need the framework file to be build properly. ANE is separate file, isn't it in case of IOS? We do include the framework separately in IOS build as you described.
The framework file `ANE-Exponea/build/Frameworks/ExponeaSDK.framework/` is old - and it seems you didn't update it after rebuild. 
The only updated framework file I found was `ANE-Exponea/platform/ios/Exponea/ExponeaSDK.framework/`
So we just need the correctly built framework that would upload to AppStore.

**Comment by gsario** [comment]
@marchbold we managed to build the Exponea Framework inhouse, and upload to AppStore was ok (used your last built ANE together with newly built framework). But, the size of the our built framework is 512KB vs your 1.3MB in previous working version from begining of August. 
The only thing changed was a text value of event name in the source code. What can be such big size difference reason? Who is building the right way? And who is not? ))

**Comment by marchbold** [comment]
Sounds like we may have been using a debug version of the framework previously, not really sure, I actually don't really remember building the framework, I thought it was supplied somewhere?

**Comment by gsario** [comment]
@marchbold, can you please build the new version properly and put in the the 'build' folder so the ANE files are correct?

**Comment by marchbold** [comment]
Sure, email me the framework and I'll build it for you.

**Comment by gsario** [comment]
Can you build it from this repo & branch?
https://github.com/plexonic/exponea-ios-sdk/tree/payment-event-fix

**Comment by marchbold** [comment]
Ah okay, I'll build it for you and rebuild the ANE.

**Comment by gsario** [comment]
@marchbold i am sorry but your build is from wrong sources. The changed sources are here: https://github.com/plexonic/exponea-ios-sdk/tree/payment-event-fix

I tried your build and it tracks old event name. Please fix.

**Comment by marchbold** [comment]
That was the code I used

**Comment by marchbold** [comment]
Oh it's in a branch on that repository?
